docs_pw = "Baustelle"
del_pw = "Baustelle"
repo = "https://github.com/Steet1Net/Baustelle.py"

[connections.mysql]
dialect = "mysql"
host = "192.168.100.100"    # change to host
database = "Baustelle"  # change to database name
username = "default"    # change to username
password = "****"   # chgnge to password
